name: Marine Energy South Africa
favicon: null
layout_spectrum: 0.28842443763278425
typography_spectrum: 0.34412838937714696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdde9'
    - '#00334b'
    - '#62a6bd'
    - '#36596f'
    - '#0e809a'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.1367890841793269
  rhythmicContrast: 0.5
purpose: []
